[package]
name = "lets_ls"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
lsp-server = "0.7.8"
lsp-types = "0.97.0"
serde_json = "1.0.133"
streaming-iterator = "0.1.9"
tree-sitter = "0.24.5"
tree-sitter-yaml = "0.7.0"
